import { Router, type Request, type Response } from "express";
import { PrivacyService } from "../services/privacyService.js";
import { MigrationService } from "../services/migrationService.js";
import { query } from "../db/index.js";

export const privacyRouter = Router();

/**
 * POST /api/private/deposit
 * Create a sealed ZK deposit commitment for a private trust
 */
privacyRouter.post(["/private/deposit", "/deposit"], async (req: Request, res: Response) => {
  try {
    const { trustId, commitment, nullifier, ciphertext, blockNumber } = req.body;
    if (!trustId || !commitment || !ciphertext) {
      return res.status(400).json({ error: "Missing trustId, commitment, or ciphertext" });
    }

    const commitmentId = await PrivacyService.addCommitment({
      trustId: parseInt(trustId, 10),
      commitment,
      nullifier,
      ciphertext,
      blockNumber: blockNumber ? parseInt(blockNumber, 10) : 0,
    });

    res.json({ success: true, commitmentId, status: "indexed" });
  } catch (err: any) {
    console.error("Error in /private/deposit:", err);
    res.status(500).json({ error: err.message || "Failed to record commitment" });
  }
});

/**
 * GET /api/private/trust/:id
 * Retrieve encrypted terms, cipher letter, and commitments for client-side decryption
 */
privacyRouter.get(["/private/trust/:id", "/trust/:id"], async (req: Request, res: Response) => {
  try {
    const trustId = parseInt(req.params.id, 10);
    if (isNaN(trustId)) {
      return res.status(400).json({ error: "Invalid trust ID" });
    }

    const termsData = await PrivacyService.getPrivateTerms(trustId);
    if (!termsData) {
      return res.status(404).json({ error: `Private trust #${trustId} not found` });
    }

    const commitments = await PrivacyService.getCommitments(trustId);

    res.json({
      trustId,
      mode: termsData.mode,
      termsHash: termsData.termsHash,
      cipherTerms: termsData.cipherTerms,
      cipherLetter: termsData.cipherLetter,
      ladder: termsData.ladder,
      commitments,
    });
  } catch (err: any) {
    console.error("Error in /private/trust/:id:", err);
    res.status(500).json({ error: err.message || "Failed to fetch private trust details" });
  }
});

/**
 * POST /api/private/heartbeat
 * Gasless relayed heartbeat check-in signed from stealth key.
 *
 * Disabled: verifyPrivateHeartbeat only checks that relayerAddress signed
 * the message, never that relayerAddress is actually bound to this trust's
 * grantor — any caller can self-sign with a throwaway key and reset any
 * trust's status to 'active' with a fresh 180-day deadline, including
 * reverting an already-triggered succession (same class of bug fixed on
 * the public heartbeat route, but with no authorization check at all here).
 * Confirmed unused by any frontend UI before disabling. Re-enable once
 * stealthKeyHash is verified against a real registered beneficiary/grantor
 * binding, per docs/Heirloom Private Legacy.pdf Feature 1.
 */
privacyRouter.post(["/private/heartbeat", "/heartbeat"], async (_req: Request, res: Response) => {
  res.status(501).json({
    error: "Private heartbeat is temporarily disabled pending cryptographic authorization binding the signer to the trust.",
  });
});

/**
 * GET /api/proofs/solvency
 * Solvency proof for the multi-asset shielded pool
 */
privacyRouter.get(["/proofs/solvency", "/solvency"], async (_req: Request, res: Response) => {
  try {
    const summary = await PrivacyService.getSolvencySummary();
    res.json(summary);
  } catch (err: any) {
    res.status(500).json({ error: "Failed to fetch solvency proof" });
  }
});

/**
 * POST /api/attest/provision
 * Create a proof-of-provision attestation (e.g. proof of holding >= $X for schools/lenders/prenups)
 *
 * Disabled: attestationHash was `0x_attestation_${Date.now()}_${nonce}` —
 * not a cryptographic proof of anything, just a formatted timestamp. A
 * school/lender/prenup counterparty reading this would see what looks like
 * a real attestation with zero backing verification. Confirmed unused by
 * any frontend UI before disabling. Re-enable only once this produces a
 * real, independently-verifiable proof.
 */
privacyRouter.post(["/attest/provision", "/provision"], async (_req: Request, res: Response) => {
  res.status(501).json({
    error: "Provision attestations are not yet implemented — no real proof is generated by this endpoint.",
  });
});

/**
 * POST /api/disclose/grant
 * Grant scoped disclosure key to an auditor, tax accountant, or regulator
 */
privacyRouter.post(["/disclose/grant", "/grant"], async (req: Request, res: Response) => {
  try {
    const { trustId, granteeAddress, cipherKey } = req.body;
    if (!trustId || !granteeAddress || !cipherKey) {
      return res.status(400).json({ error: "Missing trustId, granteeAddress, or cipherKey" });
    }

    const grantId = await PrivacyService.grantDisclosure({
      trustId: parseInt(trustId, 10),
      granteeAddress,
      cipherKey,
    });

    res.json({ success: true, grantId, status: "disclosure_granted" });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to grant disclosure" });
  }
});

/**
 * POST /api/disclose/revoke
 */
privacyRouter.post(["/disclose/revoke", "/revoke"], async (req: Request, res: Response) => {
  try {
    const { trustId, granteeAddress } = req.body;
    if (!trustId || !granteeAddress) {
      return res.status(400).json({ error: "Missing trustId or granteeAddress" });
    }

    const revoked = await PrivacyService.revokeDisclosure(parseInt(trustId, 10), granteeAddress);
    res.json({ success: revoked });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to revoke disclosure" });
  }
});

/**
 * POST /api/keys/deliver
 * Stage key handoff via KeyLadder (device-bound)
 */
privacyRouter.post(["/keys/deliver", "/deliver"], async (req: Request, res: Response) => {
  try {
    const { trustId, stageIndex, keyHash, cipherKeyPayload } = req.body;
    if (!trustId || stageIndex === undefined || !keyHash || !cipherKeyPayload) {
      return res.status(400).json({ error: "Missing key delivery fields" });
    }

    await PrivacyService.deliverStageKey({
      trustId: parseInt(trustId, 10),
      stageIndex: parseInt(stageIndex, 10),
      keyHash,
      cipherKeyPayload,
    });

    res.json({ success: true, stageIndex, status: "key_stage_delivered" });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to deliver stage key" });
  }
});

/**
 * GET /api/sets/meter
 * Returns the current anonymity set size
 */
privacyRouter.get(["/sets/meter", "/meter"], async (_req: Request, res: Response) => {
  try {
    const resDb = await query(`SELECT meter_count FROM sets WHERE name = 'rhc_mainnet_pool_v1'`);
    const row = resDb.rows[0];

    res.json({
      status: row ? "live" : "not_configured",
      anonymitySetPool: "rhc_mainnet_pool_v1",
      anonymitySetSize: row?.meter_count ?? null,
      updatedAt: new Date().toISOString(),
    });
  } catch (err: any) {
    res.status(500).json({ error: "Failed to fetch anonymity set size" });
  }
});

/**
 * POST /api/migration/migrate
 * Opt-in migration from custodial HD vault to on-chain public or private trust.
 *
 * Disabled: grantorSignature was accepted in the request body but never
 * cryptographically verified anywhere in MigrationService.migrateTrust —
 * any caller could move every non-zero balance out of any trust's vault to
 * an attacker-supplied targetVaultAddress using a trustId and an arbitrary
 * non-empty string as the "signature". Confirmed unused by any frontend UI
 * (nothing imports src/lib/heirloom/privacy.ts's client wrapper for this
 * route) before disabling. Re-enable only once this verifies a real EIP-712
 * signature from the trust's actual grantor_address, per docs/Heirloom
 * Private Legacy.pdf's action-authorization requirements.
 */
privacyRouter.post(["/migration/migrate", "/migrate"], async (_req: Request, res: Response) => {
  res.status(501).json({
    error: "Migration is temporarily disabled pending cryptographic authorization. No signature verification is implemented yet.",
  });
});

/**
 * GET /api/migration/status
 */
privacyRouter.get(["/migration/status", "/status"], async (_req: Request, res: Response) => {
  try {
    const status = await MigrationService.getCustodialBetaStatus();
    res.json(status);
  } catch (err: any) {
    res.status(500).json({ error: "Failed to fetch migration status" });
  }
});
